{% set name = "PyMinHash" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMinHash-{{ version }}.tar.gz
  sha256: 76c21c0f08f5312d461acd0300ce53b4ae4aeee864eb3396a8c7700410e60e7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - openpyxl
    - pandas
    - pytest
    - scikit-learn

test:
  imports:
    - pyminhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fritshermans/pyminhash
  summary: Efficient MinHashing
  license: MIT
  license_file: LICENSE
  description: |
    MinHashing is a very efficient way of finding similar records in a dataset based on Jaccard similarity. PyMinHash
    implements efficient minhashing for Pandas dataframes. See instructions below or look at the example notebook to get
    started.

    Developed by [Frits Hermans](https://www.linkedin.com/in/frits-hermans-data-scientist/)

    PyPI: [https://pypi.org/project/PyMinHash/](https://pypi.org/project/PyMinHash/)

  doc_url: https://pyminhash.readthedocs.io/en/latest/
  dev_url: https://github.com/fritshermans/pyminhash

extra:
  recipe-maintainers:
    - sugatoray
